apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clarte-ingress
  annotations:
    # Apply the strip-api-prefix middleware from the default namespace
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-api-prefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: clarte.local # <-- Your chosen test hostname
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: clarte-api-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clarte-web-svc
                port:
                  number: 80
