apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clarte-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: clarte.local # <-- Your chosen test hostname
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: clarte-api-svc
                port:
                  number: 80
          - path: /web
            pathType: Prefix
            backend:
              service:
                name: clarte-web-svc
                port:
                  number: 80
