apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: default # Keeping it in default for simplicity with your other tests
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami # Official image from Traefik
          ports:
            - name: web # The whoami app listens on port 80 by default
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-svc
  namespace: default # Same namespace
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 80 # Service will listen on port 80
      targetPort: web # Route to the 'web' port (80) on the pod
