apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls                   # You can name this Certificate resource
  namespace: minio-tenant1-tls            # IMPORTANT: Must be the namespace for your MinIO tenant
spec:
  secretName: minio-tls-secret       # Secret names are always required. Name of the Kubernetes Secret where cert-manager will store the cert/key

  issuerRef:
    name: selfsigned-issuer          # The ClusterIssuer we created in Step 3
    kind: ClusterIssuer              # Specifies that it's a ClusterIssuer
    # group: cert-manager.io         # Optional: usually inferred by cert-manager

  isCA: false
  usages:
    - server auth
    - client auth
  commonName: minio-s3.local.test    # A primary identifier, can be one of your DNS names

  duration: 2160h # 90d
  renewBefore: 360h # 15d
  
  dnsNames:                          # Subject Alternative Names (SANs) - critical for modern TLS
    - minio-s3.local.test            # Hostname for MinIO S3 API
    - minio-console.local.test       # Hostname for MinIO Console

  # Optional fields for self-signed certs (defaults are usually fine for local testing):
  # duration: 2160h                  # 90 days (default certificate lifespan)
  # renewBefore: 360h                # 15 days (how long before expiry cert-manager should renew it)